site_name: TheMoeWay
site_description: Learn Japanese for free, on your own, with the things you love. Acquire with anime, TheMoeWay.  
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'New Japanese Guide': 'guide.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'reading.md'
    - 'Yomichan Setup Tutorial': 'yomichan.md'
    - 'vn.md'
    - 'monolingual.md'
    - 'faq.md'
  - 'Resources':
    - 'Resources': 'resources.md'
  - 'Other':
    - 'Yomichan Custom CSS': 'yomicss.md'
  - 'About':
    - 'Contact & Support': 'contact.md'
theme:
  features:
    - navigation.instant
    - navigation.sections
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: deep purple
    accent: blue
  favicon: img/favicon.png
  logo: img/moe.svg
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
