site_name: TheMoeWay
site_description: Learn Japanese for free, on your own, with the things you love. Acquire with anime, TheMoeWay.  
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'Japanese Guide': 'guide.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'reading.md'
    - 'monolingual.md'
    - 'faq.md'
    - 'Japanese Subtitles': 'sub.md'
  - 'Visual Novels':
    - 'Learning Japanese with VNs': 'vn.md'
    - 'Installing Visual Novels': 'vn-setup.md'
  - 'Yomichan':
    - 'Yomichan Setup Tutorial': 'yomichan.md' 
    - 'Yomichan Custom CSS': 'yomicss.md'      
  - 'Resources':
    - 'Resources': 'resources.md' 
  - 'About':
    - 'Contact & Support': 'contact.md'
theme:
  features:
    - navigation.instant
    - navigation.sections
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
    accent: blue
  favicon: img/favicon.png
  logo: img/moe.svg
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      lang:
        - en
        - ja
