site_name: TheMoeWay
site_description: Moe Moe Moe Moe Moe Moe Moe Moe 
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'guide.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'reading.md'
    - 'Yomichan Setup Tutorial': 'yomichan.md'
    - 'vn.md'
    - 'monolingual.md'
    - 'faq.md'
    - 'sub.md'
  - 'About':
    - 'Contact & Support': 'contact.md'

theme:
  features:
    - navigation.instant
    - navigation.sections
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: deep purple
    accent: blue
  favicon: img/favicon.png
  logo: img/moe.svg
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde