site_name: TheMoeWay™
nav:
  - 'guide.md'
  - 'speaking.md'
  - 'animejp.md'
  - 'kanji.md'
  - 'reading.md'
  - 'vn.md'
  - 'monolingual.md'
  - 'faq.md'
  - 'sub.md'

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: purple
  favicon: img/favicon.png
  logo: img/cat.svg
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PxPaMC7CdQ
      name: Discord
copyright: New Japanese Guide is licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a> license. 